### ISSUE TITLE
Editor selection unexpectedly defaults to previous choice

### ISSUE THREAD

**Issue by jeffpaul** [10up/gutenbridge#9]
**Describe the bug**
Feedback from @tlovett1's testing:
> When I click Edit (Classic) on a post. The next post I edit opens in classic mode even if I just clicked the regular edit. Seems like it remembers your choice. That surprised me. I don't think it should remember your choice.

**Additional context**
It's possible this is coming from the Classic Editor plugin itself, so we'll want to diagnose if this is an issue with Convert to Blocks or Classic Editor.

**Comment by tlovett1** [comment]
So this is actually coded that way on purpose. To me it feels wrong. Looking for input from others.

**Comment by dinhtungdu** [comment]
https://github.com/10up/convert-to-blocks/blob/5db47f3235915171de6ffd32c086fd398c12fd97/includes/ConvertToBlocks/RevisionSupport.php#L56-L68

@tlovett1 It feels wrong to me as well. It makes sense if we view post after edit post with Classic Editor and the edit post link in the frontend directs us to the Classic Editor. But in the admin area, we don't need that behavior because we have two edit links.

**Comment by jeffpaul** [comment]
Agreed if there are two edit links that we shouldn't be hijacking that to force whatever was used previously.
